### ISSUE TITLE
dimension font

### ISSUE THREAD

**Issue by davidp88** [tadwohlrapp/google-image-search-show-image-dimensions-userscript#2]
Show the dimension's in a slightly bigger font of 9 size

**Comment by davidp88** [comment]
sir -- pls add the feature,it's important

**Comment by tadwohlrapp** [comment]
Hey @davidp88,

the image dimensions text uses the exact same font size (10px) as Google itself does when hovering an image in the Image Search sidebar:

```
font-family: Roboto-Medium,Roboto,Arial,sans-serif;
font-size: 10px;
line-height: 12px;
```

<img width="1082" alt="image" src="https://github.com/tadwohlrapp/google-image-search-show-image-dimensions-userscript/assets/2788192/64e7a010-578d-46df-8f94-2fbf05bc602d">

-----

But of course I fully understand that it might be a little too small for some users – in that case I recommend increasing the global font size in your browser or for more granular control utilizing a styling extension like [Stylebot](https://stylebot.dev/) to edit certain CSS classes on websites to your likings.

Using stylebot for example you could change the image dimensions text with the following line:
```
.img-dims p {
  font-size: 14px
}
```

Hope that helps!

**Comment by davidp88** [comment]
how to use ur above code to increase font size pls tell in detail

**Comment by tadwohlrapp** [comment]
> how to use ur above code to increase font size pls tell in detail

As I said, using Stylebot (https://stylebot.dev/). Using it is really simple; please search on Google or watch a Youtube video to learn how to do it.
